#!/bin/bash

#SBATCH -p SWAN
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00

file=P_ng_correct1ginp015

inpfile=${file}.com
outfile=${file}.out
HERE=/home/ah809/08Mar1200NMR
SCRATCH=/scratch/ah809/P_ng_correct1ginp015
mkdir ${SCRATCH}
set OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export GAUSS_EXEDIR=/usr/local/shared/gaussian/em64t/09-D01/g09
export g09root=/usr/local/shared/gaussian/em64t/09-D01
export PATH=/usr/local/shared/gaussian/em64t/09-D01/g09:$PATH
export GAUSS_SCRDIR=$SCRATCH
exe=$GAUSS_EXEDIR/g09
cp ${HERE}/${inpfile}  $SCRATCH
cd $SCRATCH
echo "Starting job $SLURM_JOBID"
echo
echo "SLURM assigned me this node:"
srun hostname
echo
ln -s $HERE/$outfile $SCRATCH/$outfile
srun $exe > $outfile < $inpfile
rm -rf ${SCRATCH}/
